# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Europe/Oslo"
      
  - package-ecosystem: "nuget"
    directory: "/build"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Europe/Oslo"
      
  - package-ecosystem: "nuget"
    directory: "/src/Intility.Extensions.Logging"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Europe/Oslo"
      
  - package-ecosystem: "nuget"
    directory: "/src/Intility.Logging.AspNetCore"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Europe/Oslo"
      
  - package-ecosystem: "nuget"
    directory: "/src/Intility.Extensions.Logging.Sentry"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Europe/Oslo"
      
  - package-ecosystem: "nuget"
    directory: "/src/Intility.Extensions.Logging.Elasticsearch"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Europe/Oslo"
      
