name: Package Distribution

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Publish packages
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.*

    - name: Publish to NuGet with Nuke
      run: ./build.sh push --nuget-api-key ${{ secrets.NUGET_API_KEY }}
      shell: bash
  create-issue:
    needs: build
    name: Create issue in template repo
    runs-on: ubuntu-latest
    steps:
      - name: Set tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Post Issue
        uses: maxkomarychev/oction-create-issue@v0.7.1
        id: create_issue
        with:
          token: ${{ secrets.TAMPLATE_REPO_TOKEN }}
          owner: Intility
          repo: templates
          title: Intility.Logging packages update to ${{ steps.vars.outputs.tag }}
          body: Package references in the dotnet templates should be updated to the latest version (${{ steps.vars.outputs.tag }})
          assignees: emilkje
          labels: dotnet
      - name: Print outputs
        run: |
          echo ${{ steps.create_issue.outputs.id }}
          echo ${{ steps.create_issue.outputs.number }}